
version: "1"
networks:
  app-tier:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local


services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.10"
    environment:
      - "ELASTIC_PASSWORD=secret"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ports:
      - "9200"
      - "9300"

  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=mydatabase"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
    ports:
      - "3306"

  redis:
    image: "redis:7.2"
    ports:
      - "6379"

  zookeeper:
    image: "bitnami/zookeeper:3.9.1"
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1

  kafka:
    image: "bitnami/kafka:3.6.0"
    networks:
      - app-tier
    ports:
      - "9092:9092"
    environment:
      - BITNAMI_DEBUG=true

#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - "kafka_data:/bitnami"
    depends_on:
      - zookeeper




#  myapp:
#    image: "pdc"
#    networks:
#      - app-tier